version: "3"
services:
  spark-master:
    image: bde2020/spark-master:2.1.0-hadoop2.8-hive-java8
    container_name: spark-master
    ports:
      - 8080:8080
      - 7077:7077
    env_file:
      - ./hadoop.env
  spark-worker:
    image: bde2020/spark-worker:2.1.0-hadoop2.8-hive-java8
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    ports:
      - "8081-8100:8081"

    env_file:
      - ./hadoop.env
  openflights-app:
    build:
      context: ./scala
    env_file:
      - ./app.env
    links:
      - spark-master:spark-master
