version: "3"
services:
  namenode:
    build:
      context: ./hadoop
    container_name: namenode
    environment:
      - CLUSTER_NAME=test
      - DATASET_FILE=./input/hadoop/For_Hire_Vehicles__FHV__-_Active.csv
    env_file:
      - ./hadoop.env
    ports:
      - 50070:50070
    depends_on:
      - datanode
  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.1.1-java8
    volumes:
      - ./data/datanode:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
    ports:
      - 50075:50075
    environment:
      - SERVICE_PRECONDITION="namenode:50070"
