version: "3"
services:
  hadoop-etl-generator:
    container_name: hadoop-etl-generator
    build:
      dockerfile: ./Hadoop-ETL/Dockerfile
      context: ./Hadoop-ETL
    env_file:
      - ./hadoop-etl.env
    volumes:
      - ./data/etl/store:/store
    environment:
      - MODE=Generator
  hadoop-etl-loader-1:
    container_name: hadoop-etl-loader-1
    build:
      dockerfile: ./Hadoop-ETL/Dockerfile
      context: ./Hadoop-ETL
    env_file:
      - ./hadoop-etl.env
    volumes:
      - ./data/etl/store:/store
    environment:
      - MODE=ETL
      - NYTimes__YearFrom=1950
      - NYTimes__MonthFrom=1
      - NYTimes__YearTo=1967
      - NYTimes__MonthTo=12
  hadoop-etl-loader-2:
    container_name: hadoop-etl-loader-2
    build:
      dockerfile: ./Hadoop-ETL/Dockerfile
      context: ./Hadoop-ETL
    env_file:
      - ./hadoop-etl.env
    volumes:
      - ./data/etl/store:/store
    environment:
      - MODE=ETL
      - NYTimes__YearFrom=1968
      - NYTimes__MonthFrom=1
      - NYTimes__YearTo=1993
      - NYTimes__MonthTo=12
  hadoop-etl-loade-3:
    container_name: hadoop-etl-loader-3
    build:
      dockerfile: ./Hadoop-ETL/Dockerfile
      context: ./Hadoop-ETL
    env_file:
      - ./hadoop-etl.env
    volumes:
      - ./data/etl/store:/store
    environment:
      - MODE=ETL
      - NYTimes__YearFrom=1994
      - NYTimes__MonthFrom=1
      - NYTimes__YearTo=2019
      - NYTimes__MonthTo=5
